//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveMoney.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountsAmounts
    {
        public int BankAccount_ID { get; set; }
        public Nullable<decimal> BankAccountAmount { get; set; }
    }
}
