//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveMoney.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesTransactions
    {
        public int ID_BankAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Name { get; set; }
    }
}
