//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveMoney.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Transaction_ID { get; set; }
        public int ID_BankAccount { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Category { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
